
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - uses: ./action
      name: "Create security assessment"
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        resource-group: ds-ms
        cluster-name: ds-ms-k8s
        code: Unhealthy
        severity: Low
        description: "This is a sample description from actions workflow"
